
import { Geist, Geist_Mono } from "next/font/google";
import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
  RedirectToSignIn
} from '@clerk/nextjs'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>      
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <header className=""> 
            <SignedOut>
               <RedirectToSignIn />
            </SignedOut>
            <SignedIn>
            <nav className="w-full fixed px-6 py-4  bg-white border-b shadow-sm dark:bg-gray-900 dark:border-gray-700">
                <div className="flex items-center justify-between max-w-7xl mx-auto">
                  <div className="text-xl font-bold text-gray-900 dark:text-white">pingDocs</div>
                  <div className="flex space-x-6 text-gray-700 dark:text-gray-300">

                    <a href="#" className="hover:text-blue-600 dark:hover:text-blue-400">Retrieval Augmented Generation (RAG)</a>
                    {/* <a href="#" className="hover:text-blue-600 dark:hover:text-blue-400">About</a>
                    <a href="#" className="hover:text-blue-600 dark:hover:text-blue-400">Contact</a> */}
                     <UserButton  />
                  </div>
                </div>
              </nav>
             
              {children}
               {/* <UserButton afterSignOutUrl="/" /> */}
            </SignedIn>
          </header>
          </body>
        </html>
    </ClerkProvider>

  );
}
